# Generated by Django 3.1.2 on 2020-11-28 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20201128_0110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('payment_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.payment'),
        ),
    ]
