# Generated by Django 3.1.2 on 2020-11-28 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20201128_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='payment',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
